// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
}
