// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogSection: typeof import('./src/components/BlogSection.vue')['default']
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    JobCard: typeof import('./src/components/JobCard.vue')['default']
    JobSection: typeof import('./src/components/JobSection.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
  }
}
